<?php
/**
 * Public Header Component
 *
 * Renders the top navigation bar for every public page. The header
 * contains the brand link, the primary navigation, the language
 * switcher, and the authentication buttons.
 *
 * CORRECTIONS (Version 11.0):
 * - Added the language switcher. The switcher is generated by
 *   getLanguageSwitcherHtml() from Solution/includes/i18n.php and
 *   appears next to the authentication buttons.
 * - Replaced every hardcoded string with a __() call. The header now
 *   renders in English or Afrikaans depending on the active language.
 * - Added a "Signed in with Google" indicator on the header for users
 *   whose session was established through Google SSO. The indicator
 *   reads from getAuthProvider() in Solution/includes/auth.php.
 * - Retains the CSRF meta tag, the security header call, the active
 *   page highlighting, the mobile menu toggle, and the role-specific
 *   dashboard and cart links.
 *
 * SOURCE: NOTES - Make use of SSO. Include multi-language support for
 *         at least two South African languages: English and Afrikaans.
 *
 * @version 11.0
 */

require_once dirname(__DIR__) . '/config/constants.php';
require_once dirname(__DIR__) . '/includes/auth.php';
require_once dirname(__DIR__) . '/includes/i18n.php';

// Set security headers for this public page.
setSecurityHeaders();

// Determine the current page for active-state highlighting.
$currentPage = basename($_SERVER['PHP_SELF']);

// Get the CSRF token if a session is active.
$csrfToken = '';

if (session_status() === PHP_SESSION_ACTIVE)
{
    $csrfToken = getCsrfToken();
}

// The provider label is shown next to the user name when the session
// was established through Google SSO.
$authProvider = function_exists('getAuthProvider') ? getAuthProvider() : null;
?>
<!DOCTYPE html>
<html lang="<?php echo escapeOutput(getCurrentLanguage()); ?>">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover">
    <meta name="csrf-token" content="<?php echo escapeOutput($csrfToken); ?>">
    <title>
        <?php echo __e('app.name'); ?>
        &middot;
        <?php echo isset($pageTitle) ? escapeOutput($pageTitle) : __e('app.tagline'); ?>
    </title>
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <link rel="stylesheet" href="<?php echo ASSETS_URL; ?>/css/style.css">
    <link rel="stylesheet" href="<?php echo ASSETS_URL; ?>/css/public.css">
</head>
<body>
    <a class="skip-link" href="#main-content"><?php echo __e('common.skip_to_content'); ?></a>

    <header class="public-header" role="banner">
        <div class="container">
            <div class="logo">
                <a href="<?php echo escapeOutput(ROOT_URL); ?>/index.php"
                   aria-label="<?php echo __e('app.name'); ?>">
                    <i class="fas fa-utensils" aria-hidden="true"></i>
                    <span><?php echo __e('app.name'); ?></span>
                </a>
            </div>

            <nav class="public-nav" aria-label="<?php echo __e('nav.primary'); ?>">
                <ul>
                    <li>
                        <a href="<?php echo escapeOutput(ROOT_URL); ?>/index.php#home"
                           class="<?php echo isActivePublicPage('index.php', $currentPage); ?>">
                            <?php echo __e('nav.home'); ?>
                        </a>
                    </li>
                    <li>
                        <a href="<?php echo escapeOutput(ROOT_URL); ?>/about.php"
                           class="<?php echo isActivePublicPage('about.php', $currentPage); ?>">
                            <?php echo __e('nav.about'); ?>
                        </a>
                    </li>
                    <li>
                        <a href="<?php echo escapeOutput(ROOT_URL); ?>/index.php#vendors">
                            <?php echo __e('nav.services'); ?>
                        </a>
                    </li>
                    <li>
                        <a href="<?php echo escapeOutput(ROOT_URL); ?>/faq.php"
                           class="<?php echo isActivePublicPage('faq.php', $currentPage); ?>">
                            <?php echo __e('nav.faq'); ?>
                        </a>
                    </li>
                    <li>
                        <a href="<?php echo escapeOutput(ROOT_URL); ?>/help.php"
                           class="<?php echo isActivePublicPage('help.php', $currentPage); ?>">
                            <?php echo __e('nav.help'); ?>
                        </a>
                    </li>

                    <?php if (isLoggedIn() && (isStudent() || isStandard())): ?>
                        <li>
                            <a href="<?php echo escapeOutput(BASE_URL); ?>/modules/student/dashboard.php">
                                <i class="fas fa-tachometer-alt" aria-hidden="true"></i>
                                <?php echo __e('nav.dashboard'); ?>
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo escapeOutput(BASE_URL); ?>/modules/student/cart.php">
                                <i class="fas fa-shopping-cart" aria-hidden="true"></i>
                                <?php echo __e('nav.cart'); ?>
                                <span id="header-cart-badge" class="cart-badge"
                                      style="display: none;">0</span>
                            </a>
                        </li>
                    <?php endif; ?>
                </ul>
            </nav>

            <div class="header-actions">
                <?php echo getLanguageSwitcherHtml(); ?>

                <div class="auth-buttons">
                    <?php if (isLoggedIn()): ?>
                        <span class="welcome-text">
                            <i class="fas fa-user-circle" aria-hidden="true"></i>
                            <?php echo escapeOutput($_SESSION['full_name'] ?? $_SESSION['username'] ?? 'User'); ?>

                            <?php if ($authProvider === 'google'): ?>
                                <span class="provider-badge" title="<?php echo __e('auth.provider_google'); ?>">
                                    <i class="fab fa-google" aria-hidden="true"></i>
                                </span>
                            <?php endif; ?>

                            <?php if (isStudent()): ?>
                                <span class="badge badge-success" style="font-size: 0.65rem; margin-left: var(--space-1);">
                                    <i class="fas fa-graduation-cap" aria-hidden="true"></i>
                                    <?php echo __e('role.student'); ?>
                                </span>
                            <?php elseif (isStandard()): ?>
                                <span class="badge badge-info" style="font-size: 0.65rem; margin-left: var(--space-1);">
                                    <i class="fas fa-user" aria-hidden="true"></i>
                                    <?php echo __e('role.standard'); ?>
                                </span>
                            <?php endif; ?>
                        </span>

                        <?php if (isAdmin()): ?>
                            <a href="<?php echo escapeOutput(BASE_URL); ?>/modules/admin/dashboard.php"
                               class="btn btn-primary btn-sm">
                                <i class="fas fa-user-shield" aria-hidden="true"></i>
                                <?php echo __e('role.admin'); ?>
                            </a>
                        <?php elseif (isVendor()): ?>
                            <a href="<?php echo escapeOutput(BASE_URL); ?>/modules/vendor/dashboard.php"
                               class="btn btn-primary btn-sm">
                                <i class="fas fa-store" aria-hidden="true"></i>
                                <?php echo __e('role.vendor'); ?>
                            </a>
                        <?php endif; ?>

                        <a href="<?php echo escapeOutput(BASE_URL); ?>/modules/auth/logout.php"
                           class="btn btn-outline btn-sm">
                            <i class="fas fa-sign-out-alt" aria-hidden="true"></i>
                            <?php echo __e('auth.sign_out'); ?>
                        </a>
                    <?php else: ?>
                        <a href="<?php echo escapeOutput(BASE_URL); ?>/modules/auth/login.php"
                           class="btn btn-outline">
                            <i class="fas fa-sign-in-alt" aria-hidden="true"></i>
                            <?php echo __e('auth.sign_in'); ?>
                        </a>
                        <a href="<?php echo escapeOutput(BASE_URL); ?>/modules/auth/register.php"
                           class="btn btn-primary">
                            <i class="fas fa-user-plus" aria-hidden="true"></i>
                            <?php echo __e('auth.sign_up'); ?>
                        </a>
                    <?php endif; ?>
                </div>
            </div>

            <button class="mobile-menu-toggle" aria-label="<?php echo __e('nav.menu'); ?>"
                    aria-expanded="false">
                <i class="fas fa-bars" aria-hidden="true"></i>
            </button>
        </div>
    </header>

    <div class="mobile-menu" aria-hidden="true">
        <nav aria-label="<?php echo __e('nav.mobile'); ?>">
            <ul>
                <li><a href="<?php echo escapeOutput(ROOT_URL); ?>/index.php#home"><?php echo __e('nav.home'); ?></a></li>
                <li><a href="<?php echo escapeOutput(ROOT_URL); ?>/about.php"><?php echo __e('nav.about'); ?></a></li>
                <li><a href="<?php echo escapeOutput(ROOT_URL); ?>/index.php#vendors"><?php echo __e('nav.services'); ?></a></li>
                <li><a href="<?php echo escapeOutput(ROOT_URL); ?>/faq.php"><?php echo __e('nav.faq'); ?></a></li>
                <li><a href="<?php echo escapeOutput(ROOT_URL); ?>/help.php"><?php echo __e('nav.help'); ?></a></li>

                <?php if (isLoggedIn() && (isStudent() || isStandard())): ?>
                    <li>
                        <a href="<?php echo escapeOutput(BASE_URL); ?>/modules/student/dashboard.php">
                            <?php echo __e('nav.dashboard'); ?>
                        </a>
                    </li>
                    <li>
                        <a href="<?php echo escapeOutput(BASE_URL); ?>/modules/student/cart.php">
                            <?php echo __e('nav.cart'); ?>
                        </a>
                    </li>
                <?php endif; ?>

                <?php if (!isLoggedIn()): ?>
                    <li>
                        <a href="<?php echo escapeOutput(BASE_URL); ?>/modules/auth/login.php">
                            <?php echo __e('auth.sign_in'); ?>
                        </a>
                    </li>
                    <li>
                        <a href="<?php echo escapeOutput(BASE_URL); ?>/modules/auth/register.php">
                            <?php echo __e('auth.sign_up'); ?>
                        </a>
                    </li>
                <?php else: ?>
                    <li>
                        <a href="<?php echo escapeOutput(BASE_URL); ?>/modules/auth/logout.php">
                            <?php echo __e('auth.sign_out'); ?>
                        </a>
                    </li>
                <?php endif; ?>
            </ul>

            <div class="mobile-language">
                <?php echo getLanguageSwitcherHtml(); ?>
            </div>
        </nav>
    </div>

    <main id="main-content">